config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	require 'sidekiq/web'
	mount Sidekiq::Web => '/sidekiq'
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get '/', as: 'index', to: 'main#index'
	get '/domain-list', as: 'domain_list', to: 'domain#domain_list'
	get '/add-domains', as: 'add_domains', to: 'domain#add_domains'
	post '/add-domains', as: 'add_domains_save', to: 'domain#add_domains_save'
	post '/del-domain', as: 'del_domain', to: 'domain#del_domain'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain.rb
# == Schema Information
#
# Table name: domains
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  domain_name :string
#  description :string
#  expire_time :datetime         not null
#  color       :string
#  job_id      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Domain < ApplicationRecord
	has_one :user

	validates_format_of :domain_name, :with => /^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix, multiline: true

	validates :domain_name, presence: true, uniqueness: { scope: [:user_id, :domain_name] }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  username               :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  confirmation_token     :string
#  unconfirmed_email      :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#

class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable, :confirmable

	has_many :domains

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	# before_action :authenticate_member!
	
end

app/controllers/domain_controller.rb
class DomainController < ApplicationController
	before_action :authenticate_user! 


	def domain_list
		#  	@result = Whois.whois("izmirbeyazesyaklimaservisi.com")
		#  	@parser = @result.parser
		#  	@sure = @parser.expires_on

		@domains = current_user.domains.all
		respond_to do |format|
			format.html
			format.json {render json: @result }
		end
	end

	def add_domains
		@domain = Domain.new
		respond_to do |format|
			format.html
			format.json {render json: @result }
		end
	end

	def add_domains_save

		@save = current_user.domains.new(domain_save_params)
		if @save.validate

			domain_info = domain_information(domain_save_params["domain_name"])
			# Eğer domain kullanılabilir durumda ise hiç kaydetme
			if domain_info.available?
				redirect_to domain_list_path, notice: "You can already buy the domain name"
				return false
			end

			@save.color = "%06x" % (rand * 0xffffff)
			@save.expire_time = domain_info.expires_on
			# Domaini kaydediyoruz
			if @save.save
				# Domaini kaydettikten sonra job'a atıyoruz
				job = DomainCheckWorker.perform_at(1.minutes.from_now, @save.id)
				# Job atadıktan sonra job_id sini domain satırına kaydediyoruz
				@save.job_id = job
				@save.save
				
				redirect_to domain_list_path, notice: "Domain successfully created"
			else
				delete_job(job)
				redirect_to domain_list_path, alert: @save.errors.full_messages.first
			end
		else
			redirect_to domain_list_path, alert: @save.errors.full_messages.first
		end
	end

	def del_domain
		domain = current_user.domains.find(params[:id])
		if domain.destroy
			delete_job(domain.job_id)
			redirect_to domain_list_path, notice: "Domain successfully deleted"
		else
			redirect_to domain_list_path, alert: domain.errors.full_messages.first
		end
	end

	private
	def all_info
		@domains = Domain.all
	end

	def domain_save_params
		params.require("domain").permit("domain_name", "description")
	end

	def domain_information(domain)
	  	result = Whois.whois(domain)
  		return result.parser
  		# @sure = @parser.expires_on
	end

	def delete_job(job_id)
		Sidekiq::ScheduledSet.new.find_job(job_id).delete
	end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domain_helper.rb
module DomainHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/domain/add_domains.html.erb
<%= simple_form_for @domain, url: add_domains_save_path do |f| %>
	<%= f.input :domain_name %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/domain/domain_list.html.erb
<h6 class="border-bottom border-gray pb-2 mb-0">Added Domains</h6>

<% @domains.each do |domain| %>
	<div class="media text-muted pt-3">
		<img data-src="holder.js/32x32?theme=thumb&bg=<%= domain.color %>&fg=<%= domain.color %>&size=1" alt="" class="mr-2 rounded">
		<p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
			<strong class="d-block text-gray-dark"><%= domain.domain_name %></strong>
			<%= domain.description.blank? ? "<br>".html_safe : domain.description %>
		</p>

		<p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
			<strong class="d-block text-gray-dark">Expire Time: <%= (domain.expire_time.to_date - Date.today).to_i %> days</strong>
			<br>
		</p>
		<%= link_to 'X', del_domain_path(id: domain.id), method: :post %>
	</div>
<% end  %>

<small class="d-block text-right mt-3">
	<a href="#">More Domains</a>
</small>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">
		<meta name="google-site-verification" content="phz3TvJqeQQvtE2F-l7n_dVzKzGXuAx2vKOd_jeGvyI" />

		<title>WatchDomains</title>
		<!-- Custom styles for this template -->
		<!-- Hotjar Tracking Code for http://watchdomain.org -->
		<script>
		    (function(h,o,t,j,a,r){
		        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
		        h._hjSettings={hjid:882932,hjsv:6};
		        a=o.getElementsByTagName('head')[0];
		        r=o.createElement('script');r.async=1;
		        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
		        a.appendChild(r);
		    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
		</script>
	</head>

	<body class="bg-light">

	<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
		<a class="navbar-brand" href="#">WatchDomains</a>
		<button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
			<ul class="navbar-nav mr-auto">
				<% if user_signed_in? %>
					<li class="nav-item active">
						<a class="nav-link" href="<%= domain_list_path %>">Dashboard <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="<%= edit_user_registration_path %>">Profile</a>
					</li>

					<li class="nav-item pull-right">
						<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
					</li>
				<% else %>
					<li class="nav-item active">
						<a class="nav-link" href="<%= new_user_registration_path %>">Register <span class="sr-only">(current)</span></a>
					</li>

					<li class="nav-item active">
						<a class="nav-link" href="<%= new_user_session_path %>">Login <span class="sr-only"></span></a>
					</li>
				<% end %>
				<!-- <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
					<div class="dropdown-menu" aria-labelledby="dropdown01">
					<a class="dropdown-item" href="#">Action</a>
					<a class="dropdown-item" href="#">Another action</a>
					<a class="dropdown-item" href="#">Something else here</a>
					</div>
				</li> -->
			</ul>
			<!--<form class="form-inline my-2 my-lg-0">
			<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form>-->
		</div>
	</nav>


	<% if user_signed_in? %>
	<div class="nav-scroller bg-white box-shadow">
		<nav class="nav nav-underline">
			<!-- <a class="nav-link active" href="#">Dashboard</a> -->
			<a class="nav-link" href="<%= domain_list_path %>">
				Domains
				<span class="badge badge-pill bg-light align-text-bottom"><%#= @domains.count %></span>
			</a>
			<a class="nav-link" href="<%= add_domains_path %>">Add Domain</a>
		</nav>
	</div>
	<% end %>

	<main role="main" class="container">
		<div class="my-3 p-3 bg-white rounded box-shadow">
			<% if flash[:notice] %>
				<div class="alert alert-success"><%= flash[:notice] %></div>
			<% end %>

			<% if flash[:alert] %>
				<div class="alert alert-danger"><%= flash[:alert] %></div>
			<% end %>
			
			<%= yield %>
		</div>
	</main>
  </body>
</html>
<script>
	document.addEventListener('turbolinks:load', function(){
		Holder.run();
	});
</script>

app/views/main/index.html.erb
<h2>What does do the Watchdomain?</h2>
Watchdomain give your to domain check with whois information. <br>
Watchdomain only control to give your domain with information of whois. If your domain status is available, watchdomain will send e-mail. Watchdomain is completely free system.

<h4 style="margin-top: 20px">How to use watchdomain?</h4>
First, you should new <a href="<%= new_user_registration_path %>">registration</a> and then must confirmation your e-mail. Later you can login. <br>
After that press to <b>Add Domain</b> button. Write down the domain address you want to follow along with the description. Later wait for e-mail to inform you.

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>